### ISSUE TITLE
Getting Error 

### ISSUE THREAD

**Issue by morningphase** [tfjmp/xanthus#9]
I was tring to run 'xanthus run simple.xanthus',and the error info is :

```
root@iZbp1erbsh5dyxp832kqgiZ:~# xanthus run simple.xanthus
Traceback (most recent call last):
        3: from /usr/local/bin/xanthus:23:in `<main>'
        2: from /usr/local/bin/xanthus:23:in `load'
        1: from /var/lib/gems/2.5.0/gems/xanthus-0.2.3/bin/xanthus:13:in `<top (required)>'
/var/lib/gems/2.5.0/gems/xanthus-0.2.3/bin/xanthus:13:in `load': cannot load such file -- ./.xanthus (LoadError)
```

I'm wondering why this happened

**Comment by morningphase** [comment]
@tfjmp I'm gettting this error:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.


Command: ["startvm", "26a73694-5685-443b-9d5d-c07937012ff4", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```
I'm wondering what can I do to tackle this problem?

**Comment by morningphase** [comment]
@tfjmp Now I tackle the previous problem but get another problem.

```
vagrant@localhost's password: 
    default: scp: /var/log/audit/audit.log: Permission denied
    default: 
==> default: Trigger run failed
==> default: A script exited with an unacceptable exit code 1.
A script exited with an unacceptable exit code 1.
```
How can I deal with the "Permission denied" problem ?

**Comment by tfjmp** [comment]
Are you running one of the provided examples?

**Comment by morningphase** [comment]
@tfjmp Yes, I am running the example in https://github.com/tfjmp/xanthus/blob/master/example/audit/.xanthus  .
And I think the reason might be that I have to enter a password when getting the outputs, but I don't know the right password. Do you know how  I can  handle it?

**Comment by tfjmp** [comment]
```
Running experiment audit with seed 277687728604917764954684617893357506141.
Running job normal_audit-0...
Setting up host scripts...
Setting up task on machine audit...
Creating provision files...
Job normal_audit-0 done.
```

From a fresh install of everything on this machine. It works fine.

In the end, you should obtain an archive like this one [normal_audit-0.tar.gz](https://github.com/tfjmp/xanthus/files/8303878/normal_audit-0.tar.gz).

There is normally no need for any sort of password. I would suggest checking your local VirtualBox and vagrant installation. The assumption is that those tools are installed and working properly.

**Comment by morningphase** [comment]
@tfjmp Thanks! After checking vbox and vagrant installation I manage to run the script correctly.
